### ISSUE TITLE
SteamVR can't transition back into SteamVR Home

### ISSUE THREAD

**Issue by yshui** [ValveSoftware/openvr#1790]
# Step to reproduce:

1. start SteamVR
2. start a game (I was testing with The Lab)
3. close the game once it starts
4. waiting for Steam Home to start

# What I saw

Steam Home shows a single frame in HMD, before exiting.

# Other Info

SteamVR version: 2.0.10, Build Oct 31, 2023 at 18;10

Stacktrace:

```
(gdb) bt
#0  0x00007fe05493b0c8 in LfMutexUnlockRobust(LfMutex*) ()
   from .local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrclient.so
#1  0x00007fe0548ae10a in CSyncLockThread::Run() ()
   from .local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrclient.so
#2  0x00007fe05494cd79 in CThread::ThreadProc(void*) ()
   from .local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrclient.so
#3  0x00007fe0690aa9eb in start_thread (arg=<optimized out>) at pthread_create.c:444
#4  0x00007fe06912e7cc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by yshui** [comment]
OK, this should probably be opened against SteamVR-for-Linux
